version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/api"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "⬆️"
  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "⬆️"