services:
  database:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      interval: 10s
      timeout: 2s
      retries: 10
  api:
    build:
      context: api/
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - database
  ui:
    build:
      context: ui/
      dockerfile: Dockerfile
      args:
        # This needs to be changed to the url of the api
        api_url: "http://localhost:8000"
    env_file:
      - .env
    ports:
      - "8080:80"

volumes:
  postgres_data:
