services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      interval: 10s
      timeout: 2s
      retries: 10
  api:
    image: ghcr.io/mkapra/vpnctrl:latest
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data: