on:
  push:
    tags:
      - 'v*'

name: Create Release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for release build to succeed
        uses: fountainhead/action-wait-for-check@v1.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: build-release (ubuntu-latest)
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: Wait for release build to succeed
        uses: fountainhead/action-wait-for-check@v1.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: build-release (macos-latest)
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: Check for prerelease
        id: check-prerelease
        run: |
          if [[ ${{ github.ref_name }} == *"pre"* ]]; then
            echo "prerelease=true" >> $GITHUB_ENV
          else
            echo "prerelease=false" >> $GITHUB_ENV
          fi
      - uses: actions/checkout@v2
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: releasebuild.yml
          workflow_conclusion: success
          branch: main
      - name: Rename binaries
        run: |
          mkdir releases
          cp vpnctrl-client-macos-latest/client releases/vpnctrl-client-macos-${{ github.ref_name }}
          cp vpnctrl-client-ubuntu-latest/client releases/vpnctrl-client-ubuntu-${{ github.ref_name }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: ${{ env.prerelease }}
          body_path: changelog/${{ github.ref_name }}.md
          files: |
            releases/vpnctrl-client-macos-${{ github.ref_name }}
            releases/vpnctrl-client-ubuntu-${{ github.ref_name }}