on:
  push:
    tags:
      - 'v*-pre*' # Push events to matching v*-pre, i.e. v1.0-pre, v20.15.10-pre2

name: Create Release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: true
          body_path: changelog/${{ github.ref }}.md
          files: |
            vpnctrl-client-ubuntu-latest
            vpnctrl-client-macos-latest