on:
  push:
    tags:
      - 'v*-pre*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body-path: changelog/${{ github.ref }}.md
          draft: true
          prerelease: true
on:
  push:
    tags:
      - 'v*-pre*' # Push events to matching v*-pre, i.e. v1.0-pre, v20.15.10-pre2

name: Create Release
jobs:
  release:
    needs: build-release
    - uses: actions/download-artifact@v3
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        prerelease: true
        body_path: changelog/${{ github.ref }}.md
        files: |
          vpnctrl-client-ubuntu-latest
          vpnctrl-client-macos-latest