on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          body_path: changelog/${{ github.ref_name }}.md
          files: |
            vpnctrl-client-ubuntu-latest
            vpnctrl-client-macos-latest